spring.application.name=pro

# Banco H2 em memoria
spring.datasource.url=jdbc:h2:mem:graphqldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialeto JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Opcional (cria tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update

# Pra ver SQL no log
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
